### ISSUE TITLE
Portal Does Not Stay Running

### ISSUE THREAD

**Issue by pr3tty8oyfl0yd** [SlaSerX/Ministra#1]
This is a great project and much appreciated. I am having 1 small issue it seems I go and run the sudo phing and the app builds and starts, I am then able to use the portal. However it seems after a few hours then it goes down, and I have to go back to the /deploy/ directory and run the sudo phing command again.

Is there anyway to keep this running all the time? Should it be and I just have something wrong? Any ideas would be appreciated.

**Comment by SlaSerX** [comment]
try now links is updated
