### ISSUE TITLE
Link is not working

### ISSUE THREAD

**Issue by EmilioCorti** [SlaSerX/Ministra#4]
Hello, I am trying to install Ministra and the link: "http://94.177.190.104/tv/ministra-5.6.1.zip" is not working.
Can you update?

**Comment by Kbz4** [comment]
Hello! it was nice while it lasted, it's a shame to lose this script.
Thanks for everything!

**Comment by SlaSerX** [comment]
links updated

**Comment by SlaSerX** [comment]
u r welcome :)

На пн, 16.11.2020 г. в 19:56 Kbz4 <notifications@github.com> написа:
