### ISSUE TITLE
cannot install minstra auto 

### ISSUE THREAD

**Issue by konkanicantaram** [SlaSerX/Ministra#5]
cannot install minstra auto as it get stuck on

failed: Connection timed out.
Retrying.

--2020-12-12 23:31:05--  (try: 5)  http://94.177.190.104/tv/ministra-5.6.1.zip
Connecting to 94.177.190.104:80... failed: Connection timed out.
Retrying.

--2020-12-12 23:33:17--  (try: 6)  http://94.177.190.104/tv/ministra-5.6.1.zip
Connecting to 94.177.190.104:80...

please can you look in this 
thank you

please can you give me your skype id

**Comment by SlaSerX** [comment]
use this https://github.com/slaserx/stalker
